/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connect.ConnectSQLServer;
import constance.Constance;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 84392
 */
public class FThongKe extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private JPopupMenu jPopupMenu;

    /**
     * Creates new form FThongKe
     */
    public FThongKe() throws SQLException {
        conn = ConnectSQLServer.getConnection(Constance.DB_URL, Constance.USER_NAME, Constance.PASSWORD);
        initComponents();
        //showData("");
        jcbMaLoaiTB.addItem("All");
        doDuLieuVaoCombobox();

    }

    private void showData(String s) throws SQLException {

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Mã Thiết Bị", "Tên Thiết Bị"
                }
        ));
        if (conn != null) {
            try {
                String sql = "select matb,tentb from THIETBI where matb like '%" + s + "%' or tentb like '%" + s + "%' ";
                //String sql = "select matb,tentb from THIETBI";
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                rs = stmt.executeQuery(sql);

                while (rs.next()) {
                    String matb = rs.getString("matb");
                    String tentb = rs.getString("tentb");
                    String a[] = new String[]{
                        matb, tentb
                    };
                    System.out.println("" + a);
                    ((DefaultTableModel) tblThongKe.getModel()).addRow(a);

                }
            } catch (SQLException ex) {
                Logger.getLogger(FThongKe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void doDuLieuVaoCombobox() throws SQLException {
        String sql = "select maloai,tenloai from LOAITB";
        //String sql = "select tenloai from LOAITB";
        Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
        rs = stmt.executeQuery(sql);
        while (rs.next()) {
            jcbMaLoaiTB.addItem(rs.getString(1));
        }
    }

    public void showMouseRight() {

        jPopupMenu = new JPopupMenu();
        JMenu JMenuPoupFont = new JMenu("Font");
        JMenuItem jMenuItemType = new JMenuItem("Type");
        JMenuPoupFont.add(jMenuItemType);
        jPopupMenu.add(JMenuPoupFont);

    }

//    public void layDuLieuTuCombobox() throws SQLException {
//        //String sql = "select maloai,tenloai from LOAITB";
//        //String choose = (String) jcbMaLoaiTB.getSelectedItem();
//        String sql = "SELECT THIETBI.matb, THIETBI.tentb \n"
//                + "FROM   LOAITB INNER JOIN THIETBI ON LOAITB.maloai = THIETBI.maloai \n"
//                + "WHERE THIETBI.maloai = N'"+ jcbMaLoaiTB.getSelectedItem() +"'"; // 
//        Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
//        //System.out.println(choose);
//        rs = stmt.executeQuery(sql);
//        while (rs.next()) {
//            String matb = rs.getString("matb");
//            String tentb = rs.getString("tentb");
//            String a[] = new String[]{
//                matb, tentb
//            };
//            System.out.println("" + a);
//            ((DefaultTableModel) tblThongKe.getModel()).addRow(a);
//        }
//        showData("");
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbMaLoaiTB = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        btnFilter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setText("Chọn mã loại thiết bị");

        jcbMaLoaiTB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblThongKe.setRowHeight(25);
        tblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblThongKeMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblThongKe);

        btnFilter.setText("Filter");
        btnFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jcbMaLoaiTB, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnFilter))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMaLoaiTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        if (jcbMaLoaiTB.getSelectedItem().equals("All")) {
            try {
                showData("");
            } catch (SQLException ex) {
                Logger.getLogger(FThongKe.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                //String sql = "select maloai,tenloai from LOAITB";
                //String choose = (String) jcbMaLoaiTB.getSelectedItem();
                String sql = "SELECT THIETBI.matb, THIETBI.tentb \n"
                        + "FROM   LOAITB INNER JOIN THIETBI ON LOAITB.maloai = THIETBI.maloai \n"
                        + "WHERE THIETBI.maloai = N'" + jcbMaLoaiTB.getSelectedItem() + "'"; //
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
                //System.out.println(choose);
                rs = stmt.executeQuery(sql);
                while (rs.next()) {
                    String matb = rs.getString("matb");
                    String tentb = rs.getString("tentb");
                    String a[] = new String[]{
                        matb, tentb
                    };
                    System.out.println("" + a);
                    ((DefaultTableModel) tblThongKe.getModel()).addRow(a);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FThongKe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnFilterActionPerformed

    private void tblThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThongKeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblThongKeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FThongKe().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcbMaLoaiTB;
    private javax.swing.JTable tblThongKe;
    // End of variables declaration//GEN-END:variables
}
